version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'production'
        dependency-name: '*'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
