# Linear queue for the main branch.
queue_rules:
  - name: main
    conditions:
      - base=master
      # Require integration tests before merging only
      - or:
          - and:
              - '-check-failure=deployment-test'
              - or:
                  - '#commits-behind>0'
                  - queue-position<0
          - label=bypass:integration
          - check-success=deployment-test
          - check-neutral=deployment-test
          - check-skipped=deployment-test
      - or:
          - and:
              - '-check-failure=getting-started'
              - '-check-failure=getting-started (link-cli)'
              - '-check-failure=getting-started (local-npm)'
              - or:
                  - '#commits-behind>0'
                  - queue-position<0
          - label=bypass:integration
          - check-skipped=getting-started
          - and:
              - or:
                  - check-success=getting-started (link-cli)
                  - check-neutral=getting-started (link-cli)
                  - check-skipped=getting-started (link-cli)
              - or:
                  - check-success=getting-started (local-npm)
                  - check-neutral=getting-started (local-npm)
                  - check-skipped=getting-started (local-npm)

pull_request_rules:
  - name: merge to master
    conditions:
      - label=automerge:merge
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: merge
  - name: rebase updates then merge to master
    conditions:
      - label=automerge:rebase
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: merge
        update_method: rebase
  - name: squash to master
    conditions:
      - label=automerge:squash
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: squash
