codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
github_checks:
  annotations: false
parsers:
  javascript:
    enable_partials: yes
ignore:
  - 'coverage/*.json'
