codecov:
  require_ci_to_pass: true
comment:
  layout: " diff, flags, files"
  behavior: default
  hide_project_coverage: false
coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
github_checks:
  annotations: false
parsers:
  javascript:
    enable_partials: yes
ignore:
  - '**/*.json'
