chains:
  - id: agoriclocal
    name: agoric
    image: ghcr.io/agoric/agoric-sdk:dev
    numValidators: 1
    env:
      - name: DEBUG
        value: SwingSet:vat,SwingSet:ls
    genesis:
      app_state:
        staking:
          params:
            # TODO determine shortest unbonding time that doesn't affect ibc connection availability
            unbonding_time: "48h"
        swingset:
          params:
            bootstrap_vat_config: "@agoric/vm-config/decentral-devnet-config.json"
    faucet:
      enabled: false
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      grpc: 9090
    resources:
      cpu: 1
      memory: 4Gi
  - id: osmosislocal
    name: osmosis
    numValidators: 1
    genesis:
      app_state:
        staking:
          params:
            unbonding_time: "48h"
        interchain_accounts:
          host_genesis_state:
            params:
              host_enabled: true
              allow_messages: ["*"]
        interchainquery:
          host_port: "icqhost"
          params:
            host_enabled: true
            allow_queries: ["*"]
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1315
      rpc: 26655
      grpc: 9093
      faucet: 8084
    resources:
      cpu: "0.5"
      memory: "500M"
  - id: gaialocal
    name: cosmoshub
    numValidators: 1
    genesis:
      app_state:
        staking:
          params:
            unbonding_time: "48h"
        interchain_accounts:
          host_genesis_state:
            params:
              host_enabled: true
              allow_messages: ["*"]
    faucet:
      enabled: true
    ports:
      rest: 1314
      rpc: 26654
      grpc: 9092
      faucet: 8083
    resources:
      cpu: "0.5"
      memory: "500M"

relayers:
  - name: osmosis-gaia
    type: hermes
    replicas: 1
    chains:
      - osmosislocal
      - gaialocal
    resources:
      cpu: "0.2"
      memory: "200M"
  - name: agoric-osmosis
    type: hermes
    replicas: 1
    chains:
      - agoriclocal
      - osmosislocal
    resources:
      cpu: "0.2"
      memory: "200M"
  - name: agoric-gaia
    type: hermes
    replicas: 1
    chains:
      - agoriclocal
      - gaialocal
    resources:
      cpu: "0.2"
      memory: "200M"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
      cpu: "0.2"
      memory: "200M"

exposer:
  resources:
    cpu: "0.2"
    memory: "200M"

faucet:
  resources:
    cpu: "0.2"
    memory: "200M"
