---

- hosts: "{{ service }}"
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  strategy: free
  vars:
    - service: ag-chain-cosmos
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/' + service + '/chain-name.txt') }}"
    - STAKER: ag-staker
    - STAKER_INIT_COINS: 62000000ubld
    - STAKER_SELF_DELEGATION: 50000000ubld
    - HELPER_BINARY: "{{lookup('env', 'GOPATH') or '/usr/local'}}/bin/ag-cosmos-helper"
    - APPDIR: "{{lookup('pipe', 'pwd')}}/../.."
  roles:
    - copy
    - init
    - init-cosmos
    - fetch-cosmos
