version: "2.2"
services:
  ag-solo:
    # This tag needs to be the SDK used by the $NETCONFIG_URL
    #  SDK_TAG=agoricdev-10
    image: agoric/agoric-sdk:${SDK_TAG}
    # ISSUE: 127.0.0.1? not a docker network?
    ports:
      # enable https://localhost:26657 for RPC
      - 26657:26657
    volumes:
      - "ag-solo-state:/state"
      - "$HOME/.agoric:/root/.agoric"
    environment:
      - "AG_SOLO_BASEDIR=/state/${SOLO_HOME:-agoriclocal}"
    entrypoint: ag-solo
    command:
      - setup
      - --webhost=0.0.0.0
      - --webport=${PORT:-8000}
      - --netconfig=${NETCONFIG_URL:-https://stage.agoric.net/network-config}
volumes:
  ag-solo-state:
