name: Agoric SDK restore Golang build
description: 'Set up Golang environment and restore cached built files'

inputs:
  go-version:
    description: 'The version of Go to use'
    required: true

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo GOPATH="$HOME/go" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - uses: kenchan0130/actions-system-info@master
      id: system-info
    - name: cache Go modules
      id: cache
      uses: actions/cache@v1
      with:
        path: ${{ env.GOPATH }}/pkg/mod
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-go-${{ inputs.go-version }}-built-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-go-${{ inputs.go-version }}-built-
    - name: go mod download
      run: go mod download
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
