name: Agoric SDK restore Golang build
description: 'Set up Golang environment and restore cached built files'

inputs:
  go-version:
    description: 'The version of Go to use'
    required: true

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo GOPATH="$HOME/go" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - name: cache Go modules
      uses: actions/cache@v1
      with:
        path: ${{ env.GOPATH }}/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('packages/cosmic-swingset/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go mod download
      run: go mod download
      shell: bash
      if: steps.built.outputs.cache-hit != 'true'
