exporters:
  file:
    path: $EXPORT_FILE

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: prometheus
          scrape_interval: 10s
          static_configs:
            - targets:
                - 0.0.0.0:$OTEL_EXPORTER_PROMETHEUS_PORT

service:
  pipelines:
    metrics:
      exporters:
        - file
      receivers:
        - prometheus
  telemetry:
    logs:
      level: debug
