exporters:
  file:
    flush_interval: 5
    path: $EXPORT_DIRECTORY/metrics.json

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: prometheus
          scrape_interval: 10s
          static_configs:
            - targets:
                - localhost:$OTEL_EXPORTER_PROMETHEUS_PORT

service:
  pipelines:
    metrics:
      exporters:
        - file
      receivers:
        - prometheus
