name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      # $default-branch
      - master
      - release-pismo
  pull_request:
  merge_group:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
          cache: false
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # golangci-lint version and command line arguments
          version: latest # if possible, don't pin to a specific version
          args: --timeout=3m
          # for pull requests, show only new issues
          only-new-issues: true
