name: Test Golang

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# set ESM_DISABLE_CACHE=true (will be JSON parsed)
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-golang
        with:
          go-version: 1.18
      - name: go test
        run: cd golang && go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage reports to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v3
